spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecomptaia_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@ecomptaia.com
    password: ${MAIL_PASSWORD:your-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  email:
    support: support@ecomptaia.com
    noreply: noreply@ecomptaia.com

logging:
  level:
    com.ecomptaia: INFO
    org.springframework: WARN
    org.hibernate: WARN