export enum UserRole {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ACCOUNTANT = 'ROLE_ACCOUNTANT',
  MANAGER = 'ROLE_MANAGER',
  AUDITOR = 'ROLE_AUDITOR',
  HR_MANAGER = 'ROLE_HR_MANAGER',
  FINANCE_MANAGER = 'ROLE_FINANCE_MANAGER',
  IT_ADMIN = 'ROLE_IT_ADMIN',
  VIEWER = 'ROLE_VIEWER'
}

export enum UserPermission {
  // Dashboard permissions
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_FINANCIAL_DASHBOARD = 'VIEW_FINANCIAL_DASHBOARD',
  VIEW_OPERATIONAL_DASHBOARD = 'VIEW_OPERATIONAL_DASHBOARD',
  
  // Accounting permissions
  VIEW_ACCOUNTING = 'VIEW_ACCOUNTING',
  CREATE_JOURNAL_ENTRY = 'CREATE_JOURNAL_ENTRY',
  EDIT_JOURNAL_ENTRY = 'EDIT_JOURNAL_ENTRY',
  DELETE_JOURNAL_ENTRY = 'DELETE_JOURNAL_ENTRY',
  APPROVE_JOURNAL_ENTRY = 'APPROVE_JOURNAL_ENTRY',
  VIEW_REPORTS = 'VIEW_REPORTS',
  GENERATE_REPORTS = 'GENERATE_REPORTS',
  
  // HR permissions
  VIEW_HR = 'VIEW_HR',
  MANAGE_EMPLOYEES = 'MANAGE_EMPLOYEES',
  MANAGE_PAYROLL = 'MANAGE_PAYROLL',
  MANAGE_LEAVES = 'MANAGE_LEAVES',
  
  // Third parties permissions
  VIEW_THIRD_PARTIES = 'VIEW_THIRD_PARTIES',
  MANAGE_CUSTOMERS = 'MANAGE_CUSTOMERS',
  MANAGE_SUPPLIERS = 'MANAGE_SUPPLIERS',
  
  // Asset management permissions
  VIEW_ASSETS = 'VIEW_ASSETS',
  MANAGE_ASSETS = 'MANAGE_ASSETS',
  MANAGE_INVENTORY = 'MANAGE_INVENTORY',
  
  // Document management permissions
  VIEW_DOCUMENTS = 'VIEW_DOCUMENTS',
  UPLOAD_DOCUMENTS = 'UPLOAD_DOCUMENTS',
  DELETE_DOCUMENTS = 'DELETE_DOCUMENTS',
  
  // System permissions
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_COMPANIES = 'MANAGE_COMPANIES',
  MANAGE_SYSTEM_CONFIG = 'MANAGE_SYSTEM_CONFIG',
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
  
  // AI permissions
  USE_AI_FEATURES = 'USE_AI_FEATURES',
  MANAGE_AI_MODELS = 'MANAGE_AI_MODELS',
  
  // International permissions
  MANAGE_INTERNATIONAL = 'MANAGE_INTERNATIONAL',
  MANAGE_CURRENCIES = 'MANAGE_CURRENCIES',
  MANAGE_TAXES = 'MANAGE_TAXES'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING = 'PENDING'
}


