services:
  postgres:
    image: postgres:15-alpine
    container_name: ecomptaia-postgres
    environment:
      POSTGRES_DB: ecomptaia_db
      POSTGRES_USER: ecomptaia_user
      POSTGRES_PASSWORD: ecomptaia_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ecomptaia-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: ecomptaia-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecomptaia_db
      SPRING_DATASOURCE_USERNAME: ecomptaia_user
      SPRING_DATASOURCE_PASSWORD: ecomptaia_password
      JWT_SECRET_KEY: ecomptaiaSecretKey2024ForProductionEnvironment
    depends_on:
      - postgres
    networks:
      - ecomptaia-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: ecomptaia-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ecomptaia-network

volumes:
  postgres_data:

networks:
  ecomptaia-network:
    driver: bridge
