apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      alertmanagerDatasourceUid: "alertmanager"
    secureJsonData: {}
    version: 1

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ecomptaia
    user: ecomptaia_user
    secureJsonData:
      password: ecomptaia_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false
    version: 1

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 25
      pipelineWindow: 100
      maxRetries: 3
    secureJsonData:
      password: redis_password
    version: 1

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
      handleAlerts: true
      alertmanagerCaching: true
      alertmanagerSyncInterval: 15
      disableResolveMessage: false
      evaluationTimeout: 30
      maxAttempts: 3
      sendAlertsToExternalAlertmanager: true
      url: http://alertmanager:9093
    version: 1

