spring:
  # Configuration de la base de données H2 (en mémoire)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  # Configuration H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuration SQL
  sql:
    init:
      mode: never
  
  # Configuration Flyway (désactivé pour éviter les conflits)
  flyway:
    enabled: false
  
  # Configuration Elasticsearch (désactivé pour le profil simple)
  elasticsearch:
    enabled: false

# Configuration du serveur
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api

  level:
    com.ecomptaia: INFO
    org.springframework: INFO
    servlet:
      context-path: /api
# Configuration de l'application
app:
  name: E-COMPTA-IA INTERNATIONAL
  version: 1.0.0
  environment: development
