spring:
  # Configuration de la base de données
  datasource:
    url: jdbc:h2:mem:testdb;INIT=runscript from 'classpath:data-test.sql'
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  # Configuration H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuration SQL
  sql:
    init:
      mode: never
  
  # Configuration de sécurité JWT
  security:
    jwt:
      secret: ecomptaiaSecretKey2024ForDevelopmentEnvironmentOnly
      expiration: 86400000 # 24 heures
  
  # Configuration email (développement)
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@ecomptaia.com
    password: dummy-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Configuration du serveur
server:
  port: 8080
  address: 0.0.0.0
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto

# Configuration de logging
logging:
  level:
    com.ecomptaia: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuration de l'application
app:
  name: E-COMPTA-IA INTERNATIONAL
  version: 1.0.0
  environment: development
  email:
    support: support@ecomptaia.com
    noreply: noreply@ecomptaia.com