spring:
  # Configuration de la base de données H2 pour le développement
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  # Configuration H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Configuration SQL
  sql:
    init:
      mode: never

  # Disable Redis for dev environment
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Configuration du serveur pour dev
server:
  port: 8080
  address: 0.0.0.0

# Configuration de logging pour dev
logging:
  level:
    com.ecomptaia: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"